#!/bin/bash

BRANCH=$1
BUILD=$2

echo "build image"
docker build . --build-arg BRANCH=$BRANCH -t $REGISTRY/$REPOSITORY:$BUILD
docker tag $REGISTRY/$REPOSITORY:$BUILD $REGISTRY/$REPOSITORY:$BRANCH
docker tag $REGISTRY/$REPOSITORY:$BUILD $REGISTRY/$REPOSITORY:$BRANCH-$BUILD

# push it!

echo "push base image"
docker push $REGISTRY/$REPOSITORY:$BUILD
docker push $REGISTRY/$REPOSITORY:$BRANCH
docker push $REGISTRY/$REPOSITORY:$BRANCH-$BUILD